### ISSUE TITLE
Add permissions handling

### ISSUE THREAD

**Issue by DeliciousJaffa** [DeliciousJaffa/MultiTwitchWhitelist-plugin#1]
Current implementation plan:  
Lowercase API return and config (means all config entries must be lowercase?)

yaml config of each sub tier and "all" sub plan i.e.
```yaml
permissions:  
  prime:
    perm.forprime: true
  1000:
    description: Gives access to all Inferno commands
    perm.for499: true
  2000:
    perm.for999: true
  3000:
    perm.for2499: true
  all:
    perm.forallsubs: true
```
